### ISSUE TITLE
Top Accounts by PI Balance

### ISSUE THREAD

**Issue by higorifpa** [pi-apps/ExplorePi#5]
I'm really enjoying the project, could you add the ranking of the biggest pi accounts

**Comment by 0205miss** [comment]
We are already including this feature in working list.
Thanks for your suggestions.

**Comment by higorifpa** [comment]
I would really like to see the desktop version of explorepi, do you intend to launch it?

**Comment by 0205miss** [comment]
desktop version will be made after hackathon or if we are ahead of schedule.

**Comment by higorifpa** [comment]
Do you already have a domain in mind? I really like this domain and it is free to buy
pinetchain.io
