### ISSUE TITLE
Pi Top 10 Without Some Wallets

### ISSUE THREAD

**Issue by H-G-0101** [pi-apps/ExplorePi#7]
Hello, I'm really enjoying this scan of the pi, the first native one, but in the top 10 wallets option some were left out of the ranking like pichainmall   GBCRZX73YTPTA7HSHVXNXYGJCUUKVUQMASELPXZ5WQVDUT7RLINS6N3Y   and some others, you can see the ranking here and you'll see that the top 10 is different
https://piiq.network/app/#/top10

**Comment by 0205miss** [comment]
The crawler isn't sync yet. It may need more 1-2 days to sync.

**Comment by kittie77** [comment]
hello, does explorePi have a link to the demo? I'd love to see the data. thanks
