### ISSUE TITLE
Suggestions 24h Statistics

### ISSUE THREAD

**Issue by H-G-0101** [pi-apps/ExplorePi#9]
**24h Statistics:**
Daily active accounts
Processed operations
Transactions
Payments
average payments
average transaction fee
Average time between records
transactions per second
Operations

**Comment by 0205miss** [comment]
We will look into it, and some of the data might be almost the same.
Later, We need to decide the most useful for.Thanks for suggestions.

**Comment by H-G-0101** [comment]
thanks, after finishing several functions, you can dedicate yourself to UI/UX and buy your own domain like pinetscan.io

**Comment by 0205miss** [comment]
We are scheduling to add following statistic for 24 hours in following days:
active accounts
Payments
Total Payments amount
Total Fee
